# Generated by Django 4.2.4 on 2023-08-08 14:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=300, verbose_name='نام برند')),
                ('brand_national', models.CharField(max_length=300, verbose_name='ملیت برند')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_model', models.CharField(max_length=300, unique=True, verbose_name='مدل تلفن همراه')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'مقدار مورد نظر باید بیشتر از 0 باشد')], verbose_name='قیمت')),
                ('color', models.CharField(max_length=200, verbose_name='رنگ محصول')),
                ('phone_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'مقدار مورد نظر باید بیشتر از 0 باشد.')], verbose_name='سایز گوشی همراه')),
                ('availability', models.BooleanField(default=False, verbose_name='موجود')),
                ('count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'مقدار مورد نظر باید بیشتر از 0 باشد')], verbose_name='تعداد')),
                ('country', models.CharField(max_length=300, verbose_name='کشور')),
                ('phone_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.brand', verbose_name='برند')),
            ],
            options={
                'verbose_name': 'گوشی',
                'verbose_name_plural': 'گوشی ها',
                'db_table': 'phone',
            },
        ),
    ]
