# Generated by Django 4.2.4 on 2023-08-08 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='count',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0, 'مقدار مورد نظر باید بیشتر از 0 باشد')], verbose_name='تعداد'),
        ),
    ]
