# Generated by Django 4.2.4 on 2023-08-10 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_alter_phonemodel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='nationality',
            field=models.CharField(default=0, max_length=300, verbose_name='ملیت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='count',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, 'مقدار مورد نظر باید بیشتر از 0 باشد')], verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='phone_size',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'مقدار مورد نظر باید بیشتر از 0 باشد.')], verbose_name='سایز گوشی همراه'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'مقدار مورد نظر باید بیشتر از 0 باشد')], verbose_name='قیمت'),
        ),
    ]
