# Generated by Django 4.2.4 on 2023-08-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_phonemodel_nationality_alter_phonemodel_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodel',
            name='nationality',
        ),
    ]
