# Generated by Django 4.2.4 on 2023-08-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0005_alter_phonemodel_phone_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemodel',
            name='country',
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='creator_country',
            field=models.CharField(default='korea', max_length=300, verbose_name='کشور سازنده'),
            preserve_default=False,
        ),
    ]
