# Generated by Django 4.2.4 on 2023-08-30 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phone", "0008_alter_brand_brand_national"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonemodel",
            name="total_price",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "قیمت کل را به درستی وارد بکنید "
                    )
                ],
                verbose_name="جمع قیمت محصولات",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="phonemodel",
            name="count",
            field=models.IntegerField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "تعداد گوشی ها را به درستی وارد بکنید"
                    )
                ],
                verbose_name="تعداد",
            ),
        ),
        migrations.AlterField(
            model_name="phonemodel",
            name="phone_size",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, " اندازه صفحه نمایش را به درستی وارد کنید "
                    )
                ],
                verbose_name="سایز گوشی همراه",
            ),
        ),
        migrations.AlterField(
            model_name="phonemodel",
            name="price",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "قیمت را به درستی وارد بکنید"
                    )
                ],
                verbose_name="قیمت",
            ),
        ),
    ]
